CREATE DATABASE CRUD_FACTURACION
GO
USE CRUD_FACTURACION
GO
SET DATEFORMAT DMY

CREATE TABLE FORMAS_PAGO
(
ID_FORMAPAGO INT,
FORMAPAGO VARCHAR (50),

CONSTRAINT PK_FORMAS_PAGO PRIMARY KEY (ID_FORMAPAGO)
)

CREATE TABLE ARTICULOS
(
ID_ARTICULO INT IDENTITY (1,1),
DESCRIPCION VARCHAR (50),
PRE_UNITARIO DECIMAL (10,2)

CONSTRAINT PK_ARTICULOS PRIMARY KEY (ID_ARTICULO)
)



CREATE TABLE FACTURAS
(
NRO_FACTURA INT IDENTITY (1,1),
FECHA DATETIME,
ID_FORMAPAGO INT,
CLIENTE VARCHAR (50)

CONSTRAINT PK_FACTURA PRIMARY KEY (NRO_FACTURA)
CONSTRAINT FK_FACTURA_FORMAS_PAGO FOREIGN KEY (ID_FORMAPAGO)
REFERENCES FORMAS_PAGO (ID_FORMAPAGO)
)

CREATE TABLE DETALLES_FACTURA
(
ID_DETALLE_FACTURA INT IDENTITY (1,1),
NRO_FACTURA INT,
ID_ARTICULO INT,
CANTIDAD INT

CONSTRAINT PK_DETALLES_FACTURA PRIMARY KEY (ID_DETALLE_FACTURA),
CONSTRAINT FK_DETALLES_FACTURA_FACTURAS FOREIGN KEY (NRO_FACTURA)
REFERENCES FACTURAS (NRO_FACTURA),
CONSTRAINT FK_DETALLES_FACTURA_ARTICULOS FOREIGN KEY (ID_ARTICULO)
REFERENCES ARTICULOS (ID_ARTICULO)
)

insert into FORMAS_PAGO (id_formaPago, formaPago)
values (1,'Efectivo')
insert into FORMAS_PAGO (id_formaPago, formaPago)
values (2,'Credito')
insert into FORMAS_PAGO (id_formaPago, formaPago)
values (3,'Debito')
insert into FORMAS_PAGO (id_formaPago, formaPago)
values (4,'Cheque')
insert into FORMAS_PAGO (id_formaPago, formaPago)
values (5,'Mercado Pago')

insert into ARTICULOS (descripcion, pre_unitario)
values ('Arroz',150)
insert into ARTICULOS (descripcion, pre_unitario)
values ('Fideos',150)
insert into ARTICULOS (descripcion, pre_unitario)
values ('Lentejas',150)
insert into ARTICULOS (descripcion, pre_unitario)
values ('YerbaMate',150)
insert into ARTICULOS (descripcion, pre_unitario)
values ('Vino',150)
insert into ARTICULOS (descripcion, pre_unitario)
values ('Fernet',150)
insert into ARTICULOS (descripcion, pre_unitario)
values ('Sal',150)
insert into ARTICULOS (descripcion, pre_unitario)
values ('Aceite',150)

insert into DETALLES_FACTURA(NRO_FACTURA, ID_ARTICULO,cantidad)
values(1,3,4)
insert into DETALLES_FACTURA(NRO_FACTURA, ID_ARTICULO,cantidad)
values(1,2,4)
insert into DETALLES_FACTURA(NRO_FACTURA, ID_ARTICULO,cantidad)
values(1,3,5)
insert into DETALLES_FACTURA(NRO_FACTURA, ID_ARTICULO,cantidad)
values(2,4,5)
insert into DETALLES_FACTURA(NRO_FACTURA, ID_ARTICULO,cantidad)
values(2,5,10)
insert into DETALLES_FACTURA(NRO_FACTURA, ID_ARTICULO,cantidad)
values(3,6,8)
insert into DETALLES_FACTURA(NRO_FACTURA, ID_ARTICULO,cantidad)
values(4,8,1)

insert into FACTURAS(fecha,id_formaPago,cliente)
values ('5/6/2021',1,'Toledo Bruno')
insert into FACTURAS(fecha,id_formaPago,cliente)
values ('15/12/2022',2,'Nicolas Mazzaglia')
insert into FACTURAS(fecha,id_formaPago,cliente)
values ('8/9/2021',3,'Virginia Maglier')
insert into FACTURAS(fecha,id_formaPago,cliente)
values ('2/1/2020',2,'Catalina Pissoni')
insert into FACTURAS(fecha,id_formaPago,cliente)
values ('5/6/2019',1,'Agustina Gallardo')



CREATE PROCEDURE SP_ARTICULOS
AS
BEGIN
SELECT *
FROM ARTICULOS
END

CREATE PROCEDURE SP_FORMAS_PAGO
AS
BEGIN
SELECT *
FROM FORMAS_PAGO
END


CREATE PROCEDURE SP_PROXIMO
@NEXT INT OUTPUT
AS
BEGIN
SET @NEXT = (SELECT MAX(NRO_FACTURA)+1 FROM FACTURAS);
END




CREATE PROCEDURE SP_INSERTAR_DETALLES
@NRO_FACTURA INT,
@ID_ARTICULO INT,
@CANTIDAD INT
AS
BEGIN
INSERT INTO DETALLES_FACTURA(NRO_FACTURA, ID_ARTICULO, CANTIDAD) VALUES (@NRO_FACTURA, @ID_ARTICULO, @CANTIDAD)
END

CREATE PROCEDURE SP_INSERTAR_MAESTRO
@CLIENTE VARCHAR (50), 
@ID_FORMAPAGO INT,
@FECHA DATETIME,
@NRO_FACTURA INT OUTPUT
AS
BEGIN
INSERT INTO FACTURAS (FECHA, ID_FORMAPAGO, CLIENTE) VALUES(@FECHA, @ID_FORMAPAGO, @CLIENTE)
SET @NRO_FACTURA = SCOPE_IDENTITY()
END

CREATE PROC SP_INSERTAR_DETALLE
@NRO_FACTURA INT,
@ID_ARTICULO INT,
@CANTIDAD INT
AS
BEGIN
INSERT INTO DETALLES_FACTURA (NRO_FACTURA, ID_ARTICULO, CANTIDAD) VALUES(@NRO_FACTURA, @ID_ARTICULO, @CANTIDAD)
END


select *
from FACTURAS
